---
title: "R Notebook"
output: html_notebook
---

<style type="text/css">

body, td {
   font-size: 12px;
}
code.r{
  font-size: 10px;
}
pre {
  font-size: 9px
}

```{r}
library(Hmisc)
library(stringr)
library(R6)
library(dplyr)
devtools::load_all()
library(tg)
load('shawn_summaryM.Rdata')

```

</style>

# This one works fine
```{r, results = 'asis'}
# Lancet uses 4-digit p-values
p_digits_4 <- cell_transform(function(cell) {
  if("p" %in% names(cell)) cell$p <- form(cell$p, "%1.4f")
  cell
})
html5(summary_table(ptgroup ~ age.enroll + sex.pp + race.pp + edu + ins.pp + frailty + adl.e + faq.e +
                iqcode.score.e + icu.type + sofa + num.apache + charlson.score + ever.vent +
                vent.los.tot.eo + mean.benz.icu + mean.op.icu + mean.prop.icu + mean.dex.icu +
                mean.hal.icu + mean.sofa.icu + icudays.sevseptic.s + icu.los.tot + hosp.los +
                died.inhosp, shawn.oneobs.desc,
                after=p_digits_4),
      fragment=TRUE, inline="lancet.css", caption = NA, id="tbl1")
```

# This one looks weird
```{r, results = 'asis'}
html5(summary_table(1 ~ rbans.global.score.3 + rbans.global.score.12 +
                        trail.b.tscore.3 + trail.b.tscore.12,
                    subset(shawn.oneobs, id %in% ltpts.either),
                    after=hmisc_intercept_cleanup),
      fragment=TRUE, inline="lancet.css", caption="", id="tbl2")
#html(summaryM(rbans.global.score.3 + rbans.global.score.12 +
#                trail.b.tscore.3 + trail.b.tscore.12 ~ 1,
#              data = subset(shawn.oneobs, id %in% ltpts.either)),
#     rmarkdown = TRUE, prn = TRUE, prmsd = TRUE, brmsd = TRUE,
#     digits = 2, caption = '', middle.bold = TRUE, msdsize = markupSpecs$html$smaller)

```

# This one looks okay
```{r, results = 'asis'}
html5(summary_table(ptgroup ~ coma.s.imp + del.s.imp +
                                  ever.hypodel.imp + days.hypodel.imp + days.hypodel.exp +
                                  ever.sedhypodel.imp + days.sedhypodel.imp + days.sedhypodel.exp +
                                  ever.hyperdel.imp + days.hyperdel.imp + days.hyperdel.exp +
                                  ever.bothdel.imp + days.bothdel.imp + days.bothdel.exp +
                                  ever.onlyhypo.imp + days.onlyhypo.imp + days.onlyhypo.exp +
                                  ever.onlyhyper.imp + days.onlyhyper.imp +
                                  days.onlyhyper.exp,
                    shawn.oneobs.desc,
                    after=p_digits_4),
      fragment=TRUE, inline="lancet.css", caption="", id="tbl3")

```

# Data Frame Example
```{r, results = 'asis'}
load('exampledf.Rdata')

# Munge the data frame a bit
data <- results.rbans[,2:11]
rownames(data) <- results.rbans[,1]
data$est.ci.x <- gsub("\\\\\\n", " ", data$est.ci.x)
data$est.ci.y <- gsub("\\\\\\n", " ", data$est.ci.y)
colnames(data) <- c("Low", "High", "Est CI", "Test Statistic", "DF", "P Value", "Est CI", "Test Statistic", "DF", "P Value")

html5(summary_frame(data, colheader=c("", "", "", "Group X", "", "", "", "Group Y", "", "")),
      fragment=TRUE, inline="lancet.css", caption="", id="tbl4")

```
