---
title: "R Notebook"
output: html_notebook
---

```{r}
library(Hmisc)
load('shawn_summaryM.Rdata')

```

# This one works fine
```{r, results = 'asis'}
html(summaryM(age.enroll + sex.pp + race.pp + edu + ins.pp + frailty + adl.e + faq.e +
                iqcode.score.e + icu.type + sofa + num.apache + charlson.score + ever.vent +
                vent.los.tot.eo + mean.benz.icu + mean.op.icu + mean.prop.icu + mean.dex.icu +
                mean.hal.icu + mean.sofa.icu + icudays.sevseptic.s + icu.los.tot + hosp.los +
                died.inhosp ~ ptgroup,
              data = shawn.oneobs.desc),
     rmarkdown = TRUE, prmsd = TRUE, brmsd = TRUE,
     what = '%', npct = 'both', digits = 2, exclude1 = FALSE, long = TRUE, caption = '',
     prn = TRUE, middle.bold = TRUE, msdsize = markupSpecs$html$smaller)

```

# This one looks weird
```{r, results = 'asis'}
html(summaryM(rbans.global.score.3 + rbans.global.score.12 +
                trail.b.tscore.3 + trail.b.tscore.12 ~ 1,
              data = subset(shawn.oneobs, id %in% ltpts.either)),
     rmarkdown = TRUE, prn = TRUE, prmsd = TRUE, brmsd = TRUE,
     digits = 2, caption = '', middle.bold = TRUE, msdsize = markupSpecs$html$smaller)

```

# This one looks okay
```{r, results = 'asis'}
mental.status.table <- summaryM(coma.s.imp + del.s.imp +
                                  ever.hypodel.imp + days.hypodel.imp + days.hypodel.exp +
                                  ever.sedhypodel.imp + days.sedhypodel.imp + days.sedhypodel.exp +
                                  ever.hyperdel.imp + days.hyperdel.imp + days.hyperdel.exp +
                                  ever.bothdel.imp + days.bothdel.imp + days.bothdel.exp +
                                  ever.onlyhypo.imp + days.onlyhypo.imp + days.onlyhypo.exp +
                                  ever.onlyhyper.imp + days.onlyhyper.imp +
                                  days.onlyhyper.exp ~ ptgroup,
                                data = shawn.oneobs.desc, continuous = 5)

```

```{r print_desc_pt, results = 'asis'}
html(mental.status.table, rmarkdown = TRUE, prmsd = TRUE, brmsd = TRUE,
     what = '%', npct = 'both', digits = 2, long = TRUE, caption = '', prn = FALSE,
     middle.bold = TRUE, msdsize = markupSpecs$html$smaller)

```

Generally, things seem to be OK when there's more than one column of descriptives.
